# Client Configuration Template
client_name: "Client Name"
business_type: "Business Type"  # e.g., "Sole Proprietorship", "LLC", "Corporation"

# Contact Information
contact:
  name: "Contact Name"
  email: "contact@email.com"
  phone: "Phone Number"

# Business Details
business_details:
  industry: "Industry Type"
  tax_id: "Tax ID"  # Optional
  fiscal_year_end: "MM-DD"  # e.g., "12-31"

# Transaction Categories
custom_categories:
  - name: "Business Expenses"
    subcategories:
      - "Office Supplies"
      - "Software Subscriptions"
      - "Professional Services"
  - name: "Personal Expenses"
    subcategories:
      - "Groceries"
      - "Utilities"
      - "Entertainment"

# Processing Preferences
preferences:
  default_output_format: "csv"  # Options: "csv", "excel"
  categorization_model: "gpt-4-vision"  # Options: "gpt-4-vision", "gpt-3.5-turbo"
  batch_size: 50  # Number of transactions to process in one batch 