# Generated by Django 5.2 on 2025-04-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("business_type", models.TextField(blank=True, null=True)),
                ("business_description", models.TextField(blank=True, null=True)),
                ("contact_info", models.TextField(blank=True, null=True)),
                ("common_business_expenses", models.TextField(blank=True, null=True)),
                (
                    "custom_6A_expense_categories",
                    models.TextField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("module_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("prompt", models.TextField()),
                (
                    "llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="profiles.llmconfig",
                    ),
                ),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True, related_name="agents", to="profiles.tool"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                ("file_path", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "normalized_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("statement_start_date", models.DateField(blank=True, null=True)),
                ("statement_end_date", models.DateField(blank=True, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("transaction_id", models.IntegerField(null=True, unique=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="profiles.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedVendorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized_name", models.CharField(max_length=255)),
                ("normalized_description", models.TextField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_data",
                        to="profiles.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("other_expense", "Other Expense"),
                            ("custom_category", "Custom Category"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("tax_year", models.IntegerField()),
                (
                    "worksheet",
                    models.CharField(
                        choices=[
                            ("6A", "6A"),
                            ("Auto", "Auto"),
                            ("HomeOffice", "HomeOffice"),
                            ("Personal", "Personal"),
                            ("None", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parent_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("line_number", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="profiles.businessprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "category_name", "tax_year"),
                        name="unique_client_category_year",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("client", "transaction_id"), name="unique_transaction"
            ),
        ),
    ]
