# Generated by Django 5.2 on 2025-04-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "client_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("business_type", models.TextField(blank=True, null=True)),
                ("business_description", models.TextField(blank=True, null=True)),
                ("custom_categories", models.JSONField(blank=True, default=dict)),
                ("industry_keywords", models.JSONField(blank=True, default=list)),
                ("category_patterns", models.JSONField(blank=True, default=dict)),
                ("industry_insights", models.TextField(blank=True, null=True)),
                ("category_hierarchy", models.JSONField(blank=True, default=dict)),
                ("business_context", models.TextField(blank=True, null=True)),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, default="2023-01-01"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "category_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("tax_year", models.IntegerField()),
                (
                    "worksheet",
                    models.CharField(
                        choices=[
                            ("6A", "6A"),
                            ("Auto", "Auto"),
                            ("HomeOffice", "HomeOffice"),
                            ("Personal", "Personal"),
                            ("None", "None"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="profiles.businessprofile",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, default="2023-01-01"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "category_name", "tax_year"),
                        name="unique_client_category_year",
                    )
                ],
            },
        ),
    ]
