# Generated by Django 5.2 on 2025-04-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientexpensecategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clientexpensecategory",
            name="line_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="clientexpensecategory",
            name="parent_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="clientexpensecategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("other_expense", "Other Expense"),
                    ("custom_category", "Custom Category"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="clientexpensecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
