# Generated by Django 5.2 on 2025-04-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_transaction_unique_transaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessprofile",
            old_name="business_context",
            new_name="common_business_expenses",
        ),
        migrations.RenameField(
            model_name="businessprofile",
            old_name="industry_insights",
            new_name="contact_info",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="category_hierarchy",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="category_patterns",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="custom_categories",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="industry_keywords",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="profile_data",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="custom_6A_expense_categories",
            field=models.TextField(blank=True, null=True),
        ),
    ]
