# Generated by Django 5.2 on 2025-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_llmconfig_agent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmconfig",
            old_name="name",
            new_name="model",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="description",
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="provider",
            field=models.CharField(default="openai", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
