# Generated by Django 5.2 on 2025-04-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_tool_agent_tools"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedVendorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized_name", models.CharField(max_length=255)),
                ("normalized_description", models.TextField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_data",
                        to="profiles.transaction",
                    ),
                ),
            ],
        ),
    ]
