# Generated by Django 5.2 on 2025-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_normalizedvendordata"),
    ]

    operations = [
        migrations.AddField(
            model_name="normalizedvendordata",
            name="original_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizedvendordata",
            name="questions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizedvendordata",
            name="transaction_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
