# Generated by Django 5.2 on 2025-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_tool_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalizedvendordata",
            name="confidence",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tool",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
