# Generated by Django 5.2 on 2025-04-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_alter_normalizedvendordata_confidence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="normalizedvendordata",
            name="original_context",
        ),
        migrations.RemoveField(
            model_name="normalizedvendordata",
            name="questions",
        ),
        migrations.AddField(
            model_name="normalizedvendordata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="normalizedvendordata",
            name="tools_used",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="normalizedvendordata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="normalizedvendordata",
            name="confidence",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="normalizedvendordata",
            name="normalized_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
