# Generated by Django 5.2 on 2025-04-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0043_auto_20250416_2358"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
