# Generated by Django 5.2 on 2025-04-17 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0047_fix_processing_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("payee_lookup", "Payee Lookup"),
                            ("classification", "Classification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_count", models.IntegerField()),
                ("processed_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_details", models.JSONField(default=dict)),
                ("task_metadata", models.JSONField(default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=models.CASCADE, to="profiles.businessprofile"
                    ),
                ),
            ],
        ),
    ]
