# Generated by Django 5.2 on 2025-04-18 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0049_add_processing_task"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ClassificationOverride",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "new_classification_type",
                            models.CharField(max_length=50, null=True, blank=True),
                        ),
                        (
                            "new_worksheet",
                            models.CharField(max_length=50, null=True, blank=True),
                        ),
                        ("notes", models.TextField(blank=True)),
                        (
                            "created_by",
                            models.CharField(max_length=255, null=True, blank=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("is_active", models.BooleanField(default=True)),
                        (
                            "transaction",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="classification_overrides",
                                to="profiles.transaction",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "verbose_name": "Classification Override",
                        "verbose_name_plural": "Classification Overrides",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
