# Generated by Django 5.2 on 2025-04-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0049_add_processing_task"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'profiles_transaction' 
                        AND column_name = 'classification_type'
                    ) THEN
                        ALTER TABLE profiles_transaction 
                        ADD COLUMN classification_type varchar(50) NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'profiles_transaction' 
                        AND column_name = 'worksheet'
                    ) THEN
                        ALTER TABLE profiles_transaction 
                        ADD COLUMN worksheet varchar(50) NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'profiles_transaction' 
                        AND column_name = 'business_percentage'
                    ) THEN
                        ALTER TABLE profiles_transaction 
                        ADD COLUMN business_percentage integer NOT NULL DEFAULT 100;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'profiles_transaction' 
                        AND column_name = 'classification_method'
                    ) THEN
                        ALTER TABLE profiles_transaction 
                        ADD COLUMN classification_method varchar(20) NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'profiles_transaction' 
                        AND column_name = 'payee_extraction_method'
                    ) THEN
                        ALTER TABLE profiles_transaction 
                        ADD COLUMN payee_extraction_method varchar(20) NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE profiles_transaction 
                DROP COLUMN IF EXISTS classification_type,
                DROP COLUMN IF EXISTS worksheet,
                DROP COLUMN IF EXISTS business_percentage,
                DROP COLUMN IF EXISTS classification_method,
                DROP COLUMN IF EXISTS payee_extraction_method;
            """,
        ),
    ]
