# Generated by Django 5.2 on 2025-04-18 00:04

import django.db.models.deletion
from django.db import migrations, models


def set_default_classification_method(apps, schema_editor):
    Transaction = apps.get_model("profiles", "Transaction")
    Transaction.objects.filter(classification_method__isnull=True).update(
        classification_method="None"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0051_create_classificationoverride"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classificationoverride",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Classification Override",
                "verbose_name_plural": "Classification Overrides",
            },
        ),
        migrations.AlterModelOptions(
            name="irsexpensecategory",
            options={"ordering": ["worksheet", "line_number"]},
        ),
        migrations.AlterModelOptions(
            name="irsworksheet",
            options={},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={},
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="common_business_expenses",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="custom_6A_expense_categories",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="generated_profile",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="processingtask",
            name="transactions",
        ),
        migrations.AlterField(
            model_name="clientexpensecategory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_expense_categories",
                to="profiles.businessprofile",
            ),
        ),
        migrations.AlterField(
            model_name="irsexpensecategory",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="irsexpensecategory",
            name="line_number",
            field=models.CharField(
                help_text="Line number on the IRS form", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="irsexpensecategory",
            name="worksheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="profiles.irsworksheet",
            ),
        ),
        migrations.AlterField(
            model_name="irsworksheet",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="irsworksheet",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RunPython(set_default_classification_method),
        migrations.AlterField(
            model_name="transaction",
            name="classification_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Classification"),
                    ("Human", "Human Override"),
                    ("None", "Not Processed"),
                ],
                default="None",
                help_text="Method used to classify the transaction",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payee_extraction_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Only"),
                    ("AI+Search", "AI with Search"),
                    ("Human", "Human Override"),
                    ("None", "Not Processed"),
                ],
                default="None",
                help_text="Method used to extract the payee information",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="searxng", max_length=50)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["query"], name="profiles_se_query_b19cd4_idx"),
                    models.Index(
                        fields=["created_at"], name="profiles_se_created_dab3a6_idx"
                    ),
                ],
            },
        ),
    ]
