# Generated by Django 5.2 on 2025-04-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0051_alter_classificationoverride_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessprofile",
            old_name="custom_6a_categories",
            new_name="additional_info",
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE profiles_businessprofile 
            DROP COLUMN IF EXISTS custom_categories;
            """,
            reverse_sql="""
            ALTER TABLE profiles_businessprofile 
            ADD COLUMN custom_categories jsonb NOT NULL DEFAULT '{}'::jsonb;
            """,
        ),
        migrations.RenameField(
            model_name="businessprofile",
            old_name="profile_data",
            new_name="custom_categories",
        ),
        migrations.AddField(
            model_name="processingtask",
            name="transactions",
            field=models.ManyToManyField(
                related_name="processing_tasks", to="profiles.transaction"
            ),
        ),
    ]
