# Generated by Django 5.2 on 2025-04-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0051_create_classificationoverride"),
        ("profiles", "0053_rename_custom_6a_categories_to_additional_info"),
    ]

    operations = []
