# Generated by Django 5.2 on 2025-04-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0053_merge_20250418_0059"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE profiles_transaction 
            ADD COLUMN normalized_description text NULL;
            """,
            reverse_sql="""
            ALTER TABLE profiles_transaction 
            DROP COLUMN IF EXISTS normalized_description;
            """,
        ),
    ]
