# Generated by Django 5.2 on 2025-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0054_add_normalized_description"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE profiles_transaction 
            ADD COLUMN IF NOT EXISTS confidence varchar(50) NULL,
            ADD COLUMN IF NOT EXISTS reasoning text NULL,
            ADD COLUMN IF NOT EXISTS business_context text NULL,
            ADD COLUMN IF NOT EXISTS questions text NULL;
            """,
            reverse_sql="""
            ALTER TABLE profiles_transaction 
            DROP COLUMN IF EXISTS confidence,
            DROP COLUMN IF EXISTS reasoning,
            DROP COLUMN IF EXISTS business_context,
            DROP COLUMN IF EXISTS questions;
            """,
        ),
    ]
