# Generated by Django 5.2 on 2025-04-12 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_add_agent_fields"),
        ("profiles", "0029_update_businessprofile_fields"),
    ]

    operations = []
