# Generated by Django 5.2 on 2025-04-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_transaction_classification_method_and_more"),
        ("profiles", "0038_combined_model_updates"),
    ]

    operations = []
