# Generated by Django 5.2 on 2025-04-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0038_remove_other_expenses_category"),
        ("profiles", "0040_fix_classification_model"),
    ]

    operations = []
