# Generated by Django 5.2 on 2025-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="classification_method",
            field=models.CharField(
                choices=[("AI", "AI Classification"), ("Human", "Human Override")],
                default="AI",
                help_text="Method used to classify the transaction",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payee_extraction_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Only"),
                    ("AI+Search", "AI with Search"),
                    ("Human", "Human Override"),
                ],
                default="AI",
                help_text="Method used to extract the payee information",
                max_length=20,
            ),
        ),
    ]
