# Generated by Django 5.2 on 2025-04-18 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessexpensecategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The IRS category this maps to (e.g., 'Other Expenses' on 6A)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.irsexpensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="classification_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Classification"),
                    ("Human", "Human Override"),
                    ("None", "Not Processed"),
                ],
                default="None",
                help_text="Method used to classify the transaction",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="classification_type",
            field=models.CharField(
                blank=True,
                help_text="Type of classification (e.g., 'business', 'personal')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payee_extraction_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Only"),
                    ("AI+Search", "AI with Search"),
                    ("Human", "Human Override"),
                    ("None", "Not Processed"),
                ],
                default="None",
                help_text="Method used to extract the payee information",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="worksheet",
            field=models.CharField(
                blank=True,
                help_text="Tax worksheet category (e.g., '6A', 'Auto', 'HomeOffice')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionclassification",
            name="classification_type",
            field=models.CharField(
                help_text="Type of classification (e.g., 'business', 'personal')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transactionclassification",
            name="worksheet",
            field=models.CharField(
                help_text="Tax worksheet category (e.g., '6A', 'Auto', 'HomeOffice')",
                max_length=50,
            ),
        ),
    ]
