# Generated by Django 5.2 on 2025-04-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_update_null_classification_methods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="classification_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Classification"),
                    ("Human", "Human Override"),
                    ("None", "Not Processed"),
                ],
                default=None,
                help_text="Method used to classify the transaction",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payee_extraction_method",
            field=models.CharField(
                choices=[
                    ("AI", "AI Only"),
                    ("AI+Search", "AI with Search"),
                    ("Human", "Human Override"),
                    ("None", "Not Processed"),
                ],
                default=None,
                help_text="Method used to extract the payee information",
                max_length=20,
            ),
        ),
    ]
